---
# file: roles/haproxy/tasks/install-Generic.yml
- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description  | default(omit) }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck  | default(omit) }}"
    gpgkey: "{{ item.gpgkey  | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    file: "{{ item.file  | default(omit) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(omit) }}"
    priority: "{{ item.priority | default('99') }}"
    enabled: "{{ item.enabled | default(true) }}"
    state: "{{ item.state | default('present') }}"
    proxy: "{{ zabbix_http_proxy | default(omit) }}"
  with_items: "{{ haproxy_repo_yum }}"
  when: haproxy_repo_yum is defined

- name: Installing HAproxy package
  package:
    name: "{{ haproxy_package }}"
