---
# file: roles/haproxy/tasks/main.yml
- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - haproxy
    - haproxy-install
    - haproxy-config
    - haproxy-sysctl
  when: haproxy_mode == "system"

- include: install.yml
  tags: [ haproxy, haproxy-install ]
  when: haproxy_mode == "system"

- include: selinux.yml
  tags: [ haproxy, haproxy-selinux ]
  when: haproxy_selinux | bool

- include: config.yml
  tags: [ haproxy, haproxy-config ]

- include: sysctl.yml
  tags: [ haproxy, haproxy-sysctl ]
  when: haproxy_mode == "system"

- include: docker.yml
  tags: [ haproxy, haproxy-docker ]
  when: haproxy_mode == "docker"
